### ISSUE TITLE
shlib: gambatte_timenow returning unexpected values

### ISSUE THREAD

**Issue by stringflow** [pokemon-speedrunning/gambatte-core#23]
gambatte_timenow is advertised as the following:
> Returns the current cycle-based time counter as dividers. (2^21/sec)

However, using the master version, the function's output seems to be stuck at `154` while playing through the Pokemon Crystal intro. Using older versions of shlib, I was able to reproduce the behavior I expected - the output advancing by `35112` for every frame of emulation.
I was able to find the offending commit: https://github.com/pokemon-speedrunning/gambatte-core/commit/4e76989ef09612a70aaa907fcdf661b4e733a5b2

**Comment by CasualPokePlayer** [comment]
The time counter would no longer be monotonic, rather it reports the internal RTC time. In this case, it's "stuck" because the game set the RTC in halt mode, which prevents time being advanced. Additionally, if the game changes the RTC, that would also be reported by the gambatte_timenow function.

**Comment by stringflow** [comment]
Unfortunately it's a breaking change for any shlib user expecting the original outputs of the function.

**Comment by CasualPokePlayer** [comment]
Looking at it, the description is somewhat "wrong", in that it's not cycle-based time necessarily, it was always reporting internals of gambatte's RTC system (meaning it would also not be "cycle based" really if you set RTC to use real time rather than cycle based time). Although I guess it is kind of right in that real time is converted to ""cycle-based"" time internally, I guess more an implementation detail?

"The game changing RTC changing the results of gambatte_timenow()" would also still be part of the old behavior (that actually wouldn't be new behavior looking at the old code).

If anything the "correct" way to get a monotonic time is to track samples emitted in gambatte_runfor calls, using gambatte_timenow would inherently be wrong if just due to the game being able to change the results regardless of whichever shlib version you used.

(If anything, the breaking change is the "freezing" part of halt mode, why it didn't freeze before is more due to a detail in how RTC worked before, although in theory you should end up seeing gambatte_timenow() go "backwards" once the game unhalts the RTC with the old shlib behavior).

**Comment by CasualPokePlayer** [comment]
Looking at it further, I'm not sure why RTC would even be halted normally here. Pokemon Crystal seems to constantly unhalt the timer if it can, so generally you shouldn't have RTC halted unless some .rtc file was loaded up which sets RTC to halt mode? (which doesn't seem possible given you have the function returning 154, which indicates it's not in initially in halt mode?)

**Comment by stringflow** [comment]
The only time the old system wouldn't work is when gen 2 resets the time counter (no save file). However this is done at a fixed point after power on, so it could be fixed with a constant offset.

> If anything the "correct" way to get a monotonic time is to track samples emitted in gambatte_runfor calls

What if you load states? Now you have to add logic to recover that time... Which is exactly what the original functionality did for you.

**Comment by CasualPokePlayer** [comment]
If we want a function to track time monotonically it probably should be a new function, as the old function inherently was never monotonic (possibly being tied to host real time and possibly being changed by the game in some manner).

Whatever this issue in particular is however, I would guess my "halt" theory is wrong, Crystal never intentionally halts the RTC, and if you're getting 154 returned that indicates it wasn't halted initially (and it shouldn't be halted initially in the first placed due to Crystal never intentionally halting the RTC).

What does the function signature look like in whatever FFI you're using to call gambatte_timenow()?

**Comment by stringflow** [comment]
The function was specifically implemented as is, only intended for shlib purposes. Even if it may not be a perfect implementation of a "timestamp" function, much code people written depends on the output of this function. Why can't the change be reverted?

**Comment by CasualPokePlayer** [comment]
Changes later on would mean you can't "revert" this, as the old time system was completely removed (it was only around at the time of that commit for HuC3, which eventually got rid of it).

I suspect the actual issue here however is due to the function not updating time registers. This was somewhat intentionally, since the old function did not cause side effects. However, this might cause the time to be "stuck" if the game is not consistently reading out RTC registers (like during Pokemon Crystal's intro), although once the game does start reading, you should see the value returned go to something "expected" (although it's probably going to be off based on however long ago the game read rtc registers)

**Comment by stringflow** [comment]
I will simply stick to older shlib version in that case. Thank you for your time.

**Comment by CasualPokePlayer** [comment]
Although, if shlib users were always expecting a monotonic time (arguably wrongly), it probably makes more sense to just scrap this function touching RTC, and just return some monotonic time that ends up stored in states.
